### ISSUE TITLE
Overview of most essential things to implement next

### ISSUE THREAD

**Issue by vidvidvid** [quest-chains/mono-repo#1]
## Edit/create screens

- [x] #2
- [x] #3
- [x] #6
- [x] #7

## Overview

- [x] #4

## NFTs

- [x] #5

## General UX improvements

- [x] #8 
- [x] #11 
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17

## Marketing

- [ ] Figure out the payment system (might make more sense to do a one-time payment instead of a stream)
  - [ ] We need a pro for that - Superfluid offered to help!
    - [ ] One option is to use a Superfluid super app to run specific logic when the stream is deleted. For example, maybe you want to remove quests or remove access to quests if the payer stops sending funds. You could use the afterAgreementTerminated callback on the Super App to run this logic there.
    - [ ] There are other options here too. For example, you could allow the DAO to create as many quests as they'd like, then open up a small stream directly to users who complete quests which also splits a % of the stream to you guys as the app creator. The DAO would have to make sure that they close the streams, but you could also have keepers run this process for you.

**Comment by dan13ram** [comment]
@vidvidvid  Superfluid streams has got me thinking. 
There could be an interesting way to incentivise users to complete quests faster so as to earn more money. Consider this:
- Upon completing a quest the DAO automatically starts a stream to the quest completer. But the stream is such that it starts with a fixed speed that gradually reduces to 0 over a period of time. That is from the time you complete the quest, over the next week or month you would get tokens streamed to you but at a decreasing pace. 
  - Example: 0.5 DAI / sec to 0 DAI / sec over 5 days => 0.5 DAI/sec on the first day. 0.4 DAI/sec on the second and so on.
- If the user completes another quest on the second day then the stream pace increases. And the stream length is also increased by the same period.
  - Example: Stream increases by another 0.5 to become 0.4 + 0.5 =  0.9 DAI/sec.
  - 1st day 0.5 DAI/sec. 2nd day 0.9 DAI/sec.  3rd day 0.8 DAI/sec. ... until 10th day 0 DAI/sec
- Note that if the user completes the quest much later then he gets less tokens since the token pace is added to the current stream pace.
- Need to consider how this would be handled if the reviewer is late to view the submissions.
